#! /bin/bash
pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &
$HOME/.config/bspwm/polybar/launch.sh &
pgrep -x dunst > /dev/null || dunst -config $HOME/.config/bspwm/dunstrc &
pgrep -x picom > /dev/null || picom --config $HOME/.config/bspwm/picom.conf &
pgrep -x greenclip > /dev/null || greenclip daemon &
feh --no-fehbg --bg-fill $HOME/.config/bspwm/out.png &
pgrep -x cycle_wall > /dev/null || cycle_wall 30m &
pgrep -x eww > /dev/null || eww daemon &
/usr/libexec/polkit-gnome-authentication-agent-1 &
xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         0
bspc config window_gap           10
bspc config split_ratio          0.5
bspc config focus_follows_pointer true
bspc config presel_feedback_color "#d4be98"

bspc rule -a feh state=fullscreen
bspc rule -a Zathura state=fullscreen
bspc rule -a TelegramDesktop desktop='^2'
bspc rule -a librewolf desktop='^1'
